---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
  labels:
    type: green
spec:
  replicas: 1
  selector:
    matchLabels:
      type: green
  template:
    metadata:
      name: nginx-pod
      labels:
        type: green
    spec:
      containers:
        - name: nginx
          image: nginx:1.24
...
